# Generated by Django 4.2 on 2024-06-04 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytodo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='終了日'),
        ),
    ]
